version: '3.1'

services:
  db:
    image: postgres:15
    container_name: odoo18_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:18
    container_name: odoo18_web
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    command: >
      odoo
      --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data: